version: '3.7'

services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - DATABASE_LOGGING=true
      - DATABASE_HOST=database
      - DATABASE_PORT=3306
      - DATABASE_NAME=nest
      - DATABASE_USER=root
      - DATABASE_PASSWORD=test
      - DATABASE_SYNC=true
      - EMAIL=no-reply@example.com
      - PORT=5000
    volumes:
      - ./src:/app/src:ro
      - ./libs:/app/libs:ro

  database:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=nest
      - MYSQL_ROOT_PASSWORD=test
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    cap_add:
      - SYS_NICE
    volumes:
      - ./database/nest:/var/lib/mysql
