version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    env_file:
      - .env
    volumes:
      - ./src:/app/src:ro
      - ./libs:/app/libs:ro

  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=lddb
      - MYSQL_ROOT_PASSWORD=test
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    cap_add:
      - SYS_NICE
    volumes:
      - ./database/lddb:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
