version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3000:5000
      - 9229:9229
    env_file:
      - .env
    volumes:
      - ./src:/app/src:ro
      - ./libs:/app/libs:ro
    depends_on:
      - db
    # command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start:debug'
    networks:
      - app-tier
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=lddb
      - MYSQL_ROOT_PASSWORD=test
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    cap_add:
      - SYS_NICE
    volumes:
      - ./database/lddb:/var/lib/mysql
    networks:
      - app-tier
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  app-tier:
    driver: bridge
